services:
  mysql:
    image: mysql
    container_name: mysql_cnt
    environment:
      - MYSQL_ROOT_PASSWORD=codeit
      - MYSQL_USER=hyunsoo
      - MYSQL_PASSWORD=910506
    ports:
      - "3307:3306"